/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'coupang' at '16. 7. 9 오후 1:43' with Gradle 2.14
 *
 * @author coupang, @date 16. 7. 9 오후 1:43
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
